# Generated by Django 2.2 on 2019-04-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annonces',
        ),
    ]
