# Generated by Django 2.2 on 2019-05-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_partage', '0009_photo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
    ]
