# Generated by Django 2.2 on 2019-06-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_partage', '0011_photo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Black_and_White',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='brightness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='photo',
            name='contrast',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='photo',
            name='sharpness',
            field=models.FloatField(default=0.0),
        ),
    ]
