# Generated by Django 2.2 on 2019-06-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_partage', '0012_auto_20190606_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Black_and_White',
            field=models.CharField(default='L', max_length=255),
        ),
    ]
