# Generated by Django 2.2 on 2019-06-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_partage', '0013_auto_20190606_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Black_and_White',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='contrast',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='sharpness',
        ),
    ]
