# Generated by Django 2.2 on 2019-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190423_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographe',
            name='followers',
            field=models.ManyToManyField(blank=True, to='accounts.Photographe'),
        ),
    ]
