# Generated by Django 2.2 on 2019-04-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190426_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='send_follow',
        ),
    ]
