# Generated by Django 2.2 on 2019-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190502_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='camera',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographe',
            name='camera',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
