# Generated by Django 2.2 on 2019-05-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_entreprise_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='camera',
        ),
    ]
