# Generated by Django 2.2 on 2019-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_client_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
