# Generated by Django 2.2 on 2019-05-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190509_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
    ]
