# Generated by Django 2.2 on 2019-05-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
