# Generated by Django 2.2 on 2019-05-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comune',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='comune',
        ),
        migrations.RemoveField(
            model_name='photographe',
            name='comune',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comune',
        ),
    ]
