# Generated by Django 2.2 on 2019-04-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Typlens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='appareil',
            name='sous_categorie',
        ),
        migrations.RemoveField(
            model_name='objectif',
            name='sous_categorie',
        ),
        migrations.AddField(
            model_name='appareil',
            name='sous_categorie',
            field=models.ManyToManyField(related_name='types_Appareil', to='Seworli_Shop.Typapp'),
        ),
        migrations.AddField(
            model_name='objectif',
            name='sous_categorie',
            field=models.ManyToManyField(related_name='types_Objectif', to='Seworli_Shop.Typlens'),
        ),
    ]
