# Generated by Django 2.2 on 2019-04-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0003_create_initial_typs'),
        ('Seworli_Shop', '0002_auto_20190430_1840'),
    ]

    operations = [
    ]
