# Generated by Django 2.2 on 2019-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0004_merge_20190430_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectif',
            name='sous_categorie',
        ),
        migrations.AddField(
            model_name='objectif',
            name='sous_categorie2',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='appareil',
            name='sous_categorie',
        ),
        migrations.AddField(
            model_name='appareil',
            name='sous_categorie',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
