# Generated by Django 2.2 on 2019-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0005_auto_20190501_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='sous_categorie',
            field=models.CharField(choices=[('Reflexe', 'Reflexe'), ('Hybride', 'Hybride'), ('Bridge', 'Bridge'), ('Compact', 'Compact')], max_length=30),
        ),
    ]
