# Generated by Django 2.2 on 2019-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0006_auto_20190501_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectif',
            name='sous_categorie2',
        ),
        migrations.AddField(
            model_name='objectif',
            name='sous_categorie',
            field=models.CharField(choices=[('Panasonic-leica', 'Panasonic-leica'), ('Panasonic-lumix', 'Panasonic-lumix'), ('Tamron', 'Tamron'), ('Canon', 'Canon'), ('Fujifilm', 'Fujifilm'), ('Nikon', 'Nikon'), ('Sigma', 'Sigma'), ('Sony', 'Sony'), ('Zeiss', 'Zeiss')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
