# Generated by Django 2.2 on 2019-05-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0008_auto_20190501_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoires',
            name='titre',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appareil',
            name='titre',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='titre',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectif',
            name='titre',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
