# Generated by Django 2.2 on 2019-05-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0009_auto_20190503_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoires',
            name='etat',
            field=models.CharField(choices=[('neuf sous emballage', 'neuf sous emballage'), ('neuf jamais utilisé', 'neuf jamais utilisé'), ('bon état', 'ébon état'), ('moyen', 'moyen')], default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appareil',
            name='etat',
            field=models.CharField(choices=[('neuf sous emballage', 'neuf sous emballage'), ('neuf jamais utilisé', 'neuf jamais utilisé'), ('bon état', 'ébon état'), ('moyen', 'moyen')], default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='etat',
            field=models.CharField(choices=[('neuf sous emballage', 'neuf sous emballage'), ('neuf jamais utilisé', 'neuf jamais utilisé'), ('bon état', 'ébon état'), ('moyen', 'moyen')], default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectif',
            name='etat',
            field=models.CharField(choices=[('neuf sous emballage', 'neuf sous emballage'), ('neuf jamais utilisé', 'neuf jamais utilisé'), ('bon état', 'ébon état'), ('moyen', 'moyen')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
