# Generated by Django 2.2 on 2019-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0010_auto_20190505_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoires',
            name='etat',
            field=models.CharField(choices=[('neuf sous emballage', 'neuf sous emballage'), ('neuf jamais utilisé', 'neuf jamais utilisé'), ('bon état', 'bon état'), ('moyen', 'moyen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='appareil',
            name='etat',
            field=models.CharField(choices=[('neuf sous emballage', 'neuf sous emballage'), ('neuf jamais utilisé', 'neuf jamais utilisé'), ('bon état', 'bon état'), ('moyen', 'moyen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='drone',
            name='etat',
            field=models.CharField(choices=[('neuf sous emballage', 'neuf sous emballage'), ('neuf jamais utilisé', 'neuf jamais utilisé'), ('bon état', 'bon état'), ('moyen', 'moyen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='objectif',
            name='etat',
            field=models.CharField(choices=[('neuf sous emballage', 'neuf sous emballage'), ('neuf jamais utilisé', 'neuf jamais utilisé'), ('bon état', 'bon état'), ('moyen', 'moyen')], max_length=30),
        ),
    ]
