# Generated by Django 2.2 on 2019-05-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0013_auto_20190505_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_a',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment_ac',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment_o',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Comment_a',
        ),
        migrations.DeleteModel(
            name='Comment_ac',
        ),
        migrations.DeleteModel(
            name='Comment_o',
        ),
    ]
