# Generated by Django 2.2 on 2019-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seworli_Shop', '0014_auto_20190505_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif',
            name='titre',
            field=models.TextField(),
        ),
    ]
